vich_uploader:
    db_driver: orm
    metadata:
        type: attribute

    mappings:
        pictureVehicle:
            uri_prefix: /uploads/imgVehicles
            upload_destination: '%kernel.project_dir%/public/uploads/imgVehicles'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

        pictureTypeOfServices:
            uri_prefix: /uploads/typeOfServices
            upload_destination: '%kernel.project_dir%/public/uploads/typeOfServices'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

        pictureOfServices:
            uri_prefix: /uploads/services
            upload_destination: '%kernel.project_dir%/public/uploads/services'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
