vich_uploader:
    db_driver: orm

    mappings:
        pictureVehicle:
            uri_prefix: /uploads/imgVehicles
            upload_destination: '%kernel.project_dir%/public/uploads/imgVehicles'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
