
parameters:

services:
    _defaults:
        autowire: true 
        autoconfigure: true 
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Service\ContactFormService:
        arguments:
            $formFactory: '@form.factory'
            $messagingRepository: '@App\Repository\MessagingRepository'

    App\Service\VehicleFormService:
        arguments:
            $formFactory: '@form.factory'
            $messagingRepository: '@App\Repository\MessagingRepository'
